# Generated by Django 5.0.7 on 2026-07-18 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kwh_used', models.FloatField(default=0)),
                ('kwh_saved', models.FloatField(default=0)),
                ('co2_reduced_kg', models.FloatField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_records', to='buildings.building')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('building', 'date')},
            },
        ),
    ]
