# Generated by Django 5.0.7 on 2026-07-18 06:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('floors', models.PositiveIntegerField(default=0)),
                ('rooms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10)),
                ('occupancy_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('room_name', models.CharField(blank=True, help_text='Simple room/location label', max_length=150)),
                ('is_on', models.BooleanField(default=False)),
                ('brightness', models.PositiveIntegerField(default=0, help_text='0-100 %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('power_w', models.FloatField(default=0)),
                ('voltage_v', models.FloatField(default=0)),
                ('current_a', models.FloatField(default=0)),
                ('operating_hours', models.PositiveIntegerField(default=0)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical')], default='healthy', max_length=10)),
                ('firmware', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='buildings.building')),
            ],
        ),
    ]
